#!/usr/bin/env node
/**
 * deps-image.mjs — resolve which dependency base image the app builds start FROM.
 *
 *   pnpm deps:image            # print what would be used, and why
 *   pnpm deps:image --tag      # print just the lockfile-hash tag (CI uses this)
 *   pnpm deps:image --resolve  # print the image ref to use, or nothing if none
 *
 * ── The contract ──────────────────────────────────────────────────────────────
 * The app Dockerfiles declare `ARG BASE_IMAGE=node:24-alpine`. That default is
 * deliberate: with no registry, no network, and no GHCR account, a clone still
 * builds exactly as it always did. This script's only job is to UPGRADE that
 * default to a prebuilt deps image when — and only when — one exists that
 * matches this project's lockfile.
 *
 * A base image whose lockfile differs is not merely useless, it is misleading:
 * the app build would still install the delta, but from a store primed with the
 * wrong content. So the tag IS the lockfile hash. A mismatch can't be silently
 * consumed, because a mismatched tag simply doesn't exist.
 *
 * ── Why probe instead of pinning ──────────────────────────────────────────────
 * Pinning the ref in the Dockerfile would make every fresh clone depend on a
 * registry being reachable and a tag being published — turning a working build
 * into a broken one for anyone offline, behind a proxy, or on a fork. Probing
 * degrades instead: no image, no problem, you just pay the install you were
 * already paying.
 */

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Where the published deps images live. Overridable for forks. */
export const DEPS_IMAGE_REPO =
  process.env.PRECAST_DEPS_IMAGE || 'ghcr.io/jacobfernandez917/precast-deps';

/** The fallback every Dockerfile already works with. */
export const FALLBACK_BASE = 'node:24-alpine';

/**
 * Hash the inputs that determine the dependency graph — the lockfile plus every
 * manifest's dependency blocks. The lockfile alone would be *almost* right, but
 * it is regenerated by `pnpm install` and can differ in ordering/metadata
 * between pnpm versions; folding in the declared ranges keeps the key stable
 * for the thing we actually care about.
 */
export function lockHash(dir = rootDir) {
  const lockPath = join(dir, 'pnpm-lock.yaml');
  if (!existsSync(lockPath)) return null;
  const h = createHash('sha256').update(readFileSync(lockPath));

  for (const rel of [
    'package.json',
    'apps/agents/package.json',
    'apps/web/package.json',
    'packages/shared/package.json',
  ]) {
    const abs = join(dir, rel);
    if (!existsSync(abs)) continue;
    const pkg = JSON.parse(readFileSync(abs, 'utf-8'));
    // Names are excluded on purpose: `pnpm rename` rewrites every workspace
    // package name, and a rename does not change one byte of the dependency
    // graph. Keying on names would give every derived project a cache miss.
    h.update(
      JSON.stringify({
        dependencies: pkg.dependencies ?? {},
        devDependencies: pkg.devDependencies ?? {},
        packageManager: pkg.packageManager ?? null,
      }),
    );
  }
  return h.digest('hex').slice(0, 16);
}

export function tagFor(dir = rootDir) {
  const h = lockHash(dir);
  return h ? `lock-${h}` : null;
}

/** Does this exact image exist in the registry? Never throws. */
function imageExists(ref) {
  const res = spawnSync('docker', ['manifest', 'inspect', ref], {
    encoding: 'utf-8',
    stdio: ['ignore', 'pipe', 'pipe'],
    timeout: 20_000,
  });
  return res.status === 0;
}

/**
 * The image ref the app builds should use, or null to keep the Dockerfile
 * default. Skipped entirely when PRECAST_DEPS_IMAGE=off, so a user who wants
 * the plain path can always have it.
 */
export function resolveBaseImage({ probe = true } = {}) {
  if ((process.env.PRECAST_DEPS_IMAGE ?? '').toLowerCase() === 'off') {
    return { ref: null, reason: 'disabled by PRECAST_DEPS_IMAGE=off' };
  }
  const tag = tagFor();
  if (!tag) return { ref: null, reason: 'no pnpm-lock.yaml to key an image on' };

  const ref = `${DEPS_IMAGE_REPO}:${tag}`;
  if (!probe) return { ref, reason: 'not probed' };
  if (imageExists(ref)) return { ref, reason: 'published image matches this lockfile' };
  return {
    ref: null,
    reason: `no published image for this lockfile (${tag}) — building deps from source`,
  };
}

function main() {
  const args = process.argv.slice(2);

  if (args.includes('--tag')) {
    const tag = tagFor();
    if (!tag) process.exit(1);
    process.stdout.write(tag + '\n');
    return;
  }

  if (args.includes('--resolve')) {
    // Consumed by `pnpm poc`: prints a ref or nothing. Never fails the caller.
    const { ref } = resolveBaseImage();
    if (ref) process.stdout.write(ref + '\n');
    return;
  }

  const tag = tagFor();
  console.log(`Dependency base image\n`);
  console.log(`  repository   ${DEPS_IMAGE_REPO}`);
  console.log(`  lockfile tag ${tag ?? '(no lockfile)'}`);
  const { ref, reason } = resolveBaseImage();
  console.log(`  resolved     ${ref ?? FALLBACK_BASE + '  (fallback)'}`);
  console.log(`  why          ${reason}\n`);
  if (!ref) {
    console.log('  Builds still work — they just install dependencies themselves.');
    console.log(`  To publish one for this lockfile, push to a branch with the`);
    console.log(`  deps-image workflow, or build it locally:\n`);
    console.log(
      `    docker build -f docker/deps.Dockerfile --build-arg PRECAST_LOCK_HASH=${tag ?? ''} \\\n` +
        `      -t ${DEPS_IMAGE_REPO}:${tag ?? 'lock-unknown'} .\n`,
    );
  }
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) main();
